package model.pojo;
// Generated 18/09/2015 21:59:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private int id;
     private String nome;
     private String sexo;
     private String telefoneNum;
     private String telefoneTipo;
     private Date dataNascimento;
     private Set<Mensagens> mensagenses = new HashSet<Mensagens>(0);
     private Set<MensagensEnviadas> mensagensenviadases = new HashSet<MensagensEnviadas>(0);
     private Set<ContatoGrupo> contatoGrupos = new HashSet<ContatoGrupo>(0);
     private Set<Ligacoes> ligacoeses = new HashSet<Ligacoes>(0);

    public Contato() {
    }

	
    public Contato(int id) {
        this.id = id;
    }
    public Contato(int id, String nome, String sexo, String telefoneNum, String telefoneTipo, Date dataNascimento, Set<Mensagens> mensagenses, Set<MensagensEnviadas> mensagensenviadases, Set<ContatoGrupo> contatoGrupos, Set<Ligacoes> ligacoeses) {
       this.id = id;
       this.nome = nome;
       this.sexo = sexo;
       this.telefoneNum = telefoneNum;
       this.telefoneTipo = telefoneTipo;
       this.dataNascimento = dataNascimento;
       this.mensagenses = mensagenses;
       this.mensagensenviadases = mensagensenviadases;
       this.contatoGrupos = contatoGrupos;
       this.ligacoeses = ligacoeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefoneNum() {
        return this.telefoneNum;
    }
    
    public void setTelefoneNum(String telefoneNum) {
        this.telefoneNum = telefoneNum;
    }
    public String getTelefoneTipo() {
        return this.telefoneTipo;
    }
    
    public void setTelefoneTipo(String telefoneTipo) {
        this.telefoneTipo = telefoneTipo;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Set<Mensagens> getMensagenses() {
        return this.mensagenses;
    }
    
    public void setMensagenses(Set<Mensagens> mensagenses) {
        this.mensagenses = mensagenses;
    }
    
    public Set<MensagensEnviadas> getMensagensenviadases() {
        return this.mensagensenviadases;
    }
    
    public void setMensagensenviadases(Set<MensagensEnviadas> mensagensenviadases) {
        this.mensagensenviadases = mensagensenviadases;
    }
    
    public Set<ContatoGrupo> getContatoGrupos() {
        return this.contatoGrupos;
    }
    
    public void setContatoGrupos(Set<ContatoGrupo> contatoGrupos) {
        this.contatoGrupos = contatoGrupos;
    }
    public Set<Ligacoes> getLigacoeses() {
        return this.ligacoeses;
    }
    
    public void setLigacoeses(Set<Ligacoes> ligacoeses) {
        this.ligacoeses = ligacoeses;
    }




}


