package model.pojo;
// Generated 18/09/2015 21:59:49 by Hibernate Tools 4.3.1



/**
 * ContatoGrupo generated by hbm2java
 */
public class ContatoGrupo  implements java.io.Serializable {


     private int id;
     private Contato contato;
     private Grupos grupos;

    public ContatoGrupo() {
    }

	
    public ContatoGrupo(int id) {
        this.id = id;
    }
    public ContatoGrupo(int id, Contato contato, Grupos grupos) {
       this.id = id;
       this.contato = contato;
       this.grupos = grupos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }




}


