package model.pojo;
// Generated 18/09/2015 21:59:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensagens generated by hbm2java
 */
public class Mensagens  implements java.io.Serializable {


     private Integer id;
     private Contato contato;
     private String conteudo;
     private Date dataHoraEnvio;
     private Boolean visualizada;

    public Mensagens() {
    }

	
    public Mensagens(int id) {
        this.id = id;
    }
    public Mensagens(Integer id, Contato contato, String conteudo, Date dataHoraEnvio, Boolean visualizada) {
       this.id = id;
       this.contato = contato;
       this.conteudo = conteudo;
       this.dataHoraEnvio = dataHoraEnvio;
       this.visualizada = visualizada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }
    public Date getDataHoraEnvio() {
        return this.dataHoraEnvio;
    }
    
    public void setDataHoraEnvio(Date dataHoraEnvio) {
        this.dataHoraEnvio = dataHoraEnvio;
    }
    public Boolean getVisualizada() {
        return this.visualizada;
    }
    
    public void setVisualizada(Boolean visualizada) {
        this.visualizada = visualizada;
    }




}


