package model.pojo;
// Generated 18/09/2015 21:59:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensagens generated by hbm2java
 */
public class MensagensEnviadas implements java.io.Serializable {


     private int id;
     private Contato contato;
     private String conteudo;
     private Date dataHoraEnvio;

    public MensagensEnviadas() {
    }

	
    public MensagensEnviadas(int id) {
        this.id = id;
    }
    public MensagensEnviadas(int id, Contato contato, String conteudo, Date dataHoraEnvio) {
       this.id = id;
       this.contato = contato;
       this.conteudo = conteudo;
       this.dataHoraEnvio = dataHoraEnvio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }
    public Date getDataHoraEnvio() {
        return this.dataHoraEnvio;
    }
    
    public void setDataHoraEnvio(Date dataHoraEnvio) {
        this.dataHoraEnvio = dataHoraEnvio;
    }

}


